# -*- coding: utf-8 -*-
"""MartonEmmaDisszertacio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2EyPLBAEp8Ln6fXalE-hvHFkuUzfo26
"""

# SZÜKSÉGES KÖNYVTÁRAK IMPORTÁLÁSA
import pandas as pd
import numpy as np

# ADATOK BETÖLTÉSE
from google.colab import files
df = pd.read_csv('Barcelona 2025.09.14.csv')
df = df.copy()

df.info()

# HIÁNYZÓ ADATOK KISZŰRÉSE
print("Hiányzó értékek száma:")
print(df.isnull().sum())

# HIÁNYZÓ ÉRTÉKEK KEZELÉSE
df = df.dropna(subset=['price'])

print("Tisztítás után:")
print(df.isnull().sum())

#ÚJ VÁTOZÓ LÉTREHOZÁSA 0-NINCS, 1-VAN ÉRTÉKELÉS
df['has_reviews'] = df['reviews_per_month'].notna().astype(int)
df.info()

# DUPLIKÁT SOROK ELLENŐRZÉSE
duplicate = df[df.duplicated()]
print("Duplikált sorok száma:", df.duplicated().sum())
df = df.drop_duplicates()
print("Tisztítás után:", df.duplicated().sum())

# ADATTÍPUSOK KONVERTÁLÁSA
df['last_review'] = pd.to_datetime(df['last_review'], errors = 'coerce')

# KATEGÓRIÁK OPTIMALIZÁLÁSA
df['neighbourhood_group'] = df['neighbourhood_group'].astype('category')
df['neighbourhood'] = df['neighbourhood'].astype('category')
df['room_type'] = df['room_type'].astype('category')

# ELLENŐRZÉS
print (df.dtypes)

# OUTLIEREK KEZELÉSE
# Price: kiszűröm a nagyon magas vagy nagyon alacsony ertekeket, percentilis alapú szűrés
# Minimum nights: kiszűröm az extrem ertekeket

upper_price_limit = df['price'].quantile(0.99)
df = df[(df['price'] > 0) & (df['price'] < upper_price_limit)]

upper_min_nights = df['minimum_nights'].quantile(0.99)
df = df[df['minimum_nights'] < upper_min_nights]

print("Tisztítás után adatsorok száma:", df.shape[0])
print(df[['price', 'minimum_nights']].describe())

df.info()
df.head(5)

print("\n" + "="*50)
print("READY FOR VISUALIZATION")
print("="*50)
print(f"Dataset shape: {df.shape}")
print(f"Price range: €{df['price'].min():.0f} - €{df['price'].max():.0f}")
print(f"Room types available: {df['room_type'].unique()}")
print(f"Missing values: {df.isnull().sum().sum()}")
print("="*50 + "\n")

#HASZNÁLT KÖNYVTÁRAK IMPORTÁLÁSA
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import time

#FUTÁSI IDŐ
def benchmark(func, repeats=10):
    times = []

    for _ in range(repeats):
        start = time.time()
        func()
        end = time.time()
        times.append(end - start)

    return np.mean(times), np.std(times)

# ELOSZLÁS
# változó: price
# Hogyan oszlanak el az Airbnb áraka Barcelonába?
# histogram

#MATPLOTLIB - DEFAULT
plt.hist(df['price'])
plt.title('Price distribution - Matplotlib')
plt.xlabel('Price')
plt.ylabel('Number of listings')
plt.show()

#MATPLOTLIB -CUSTOM
median_price = df['price'].median()
plt.figure(figsize=(10,6))
plt.hist(df['price'], bins=50, color='green', edgecolor='black', alpha=0.7)
plt.title('Price distribution - Matplotlib', fontsize=14)
plt.xlabel('Price', fontsize=12)
plt.ylabel('Number of listings', fontsize=12)
plt.axvline(median_price, color='red', linestyle='--', linewidth=2, label=f'Median: {df["price"].median():.0f} EUR')
plt.legend()
plt.show()

#MATPLOTLIB - BENCHMARK
def plot_matplotlib_hist_custom():
  median_price = df['price'].median()
  plt.figure(figsize=(10,6))
  plt.hist(df['price'], bins=50, color='green', edgecolor='black', alpha=0.7)
  plt.title('Price distribution - Matplotlib', fontsize=14)
  plt.xlabel('Price', fontsize=12)
  plt.ylabel('Number of listings', fontsize=12)
  plt.axvline(median_price, color='red', linestyle='--', linewidth=2, label=f'Median: {df["price"].median():.0f} EUR')
  plt.legend()
  plt.close()

#SEABORN - DEFAULT
sns.histplot(df['price'])
plt.title('Price distribution - Seaborn')
plt.xlabel('Price')
plt.ylabel('Number of listings')
plt.show()

#SEABORN - CUSTOM
median_price = df['price'].median()
plt.figure(figsize=(10,6))
sns.histplot(df['price'], bins=50, color='green', alpha=0.7, kde=True) #kde-val teszem be a vonalat, attol fuggoen hogy True vagy False
plt.title('Price distribution - Seaborn', fontsize=14)
plt.xlabel('Price', fontsize=12)
plt.ylabel('Number of listings', fontsize=12)
plt.axvline(median_price, color='red', linestyle='--', linewidth=2, label=f'Median: {df["price"].median():.0f} EUR')
plt.legend()
plt.show()

#SEABORN - BENCHMARK
def plot_seaborn_hist_custom():
  median_price = df['price'].median()
  plt.figure(figsize=(10,6))
  sns.histplot(df['price'], bins=50, color='green', alpha=0.7, kde=True) #kde-val teszem be a vonalat, attol fuggoen hogy True vagy False
  plt.title('Price distribution - Seaborn', fontsize=14)
  plt.xlabel('Price', fontsize=12)
  plt.ylabel('Number of listings', fontsize=12)
  plt.axvline(median_price, color='red', linestyle='--', linewidth=2, label=f'Median: {df["price"].median():.0f} EUR')
  plt.legend()
  plt.close()

#PLOTLY - DEFAULT
fig = px.histogram(df,x='price')
fig.update_layout(xaxis_title = 'Price (EUR)',
                    yaxis_title = 'Number of listings',
                    title = 'Price distribution - Plotly')

#PLOTLY - CUSTOM
median_price=df['price'].median()
fig = px.histogram(df,
                  x='price',
                  nbins=50,
                  title="Price distribution - Plotly",
                  labels={'price' : 'Price (EUR)', 'count': 'Number of listings'},
                  color_discrete_sequence=['green'])
fig.add_vline(x=median_price,
              line_dash="dash",
              line_color='red',
              annotation_text=f"Median: {df['price'].median():.0f} EUR")
fig.update_layout(xaxis_title = 'Price (EUR)',
                  yaxis_title = 'Number of listings',
                  bargap=0.1,
                  width=900,
                  height=600,
                  title_font_size=14,
                  xaxis_title_font_size=12,
                  yaxis_title_font_size=12)
fig.show()

#PLOTLY - BENCHMARK
def plot_plotly_hist_custom():
  median_price=df['price'].median()
  fig = px.histogram(df,
                    x='price',
                    nbins=50,
                    title="Price distribution - Plotly",
                    labels={'price' : 'Price (EUR)', 'count': 'Number of listings'},
                    color_discrete_sequence=['green'])
  fig.add_vline(x=median_price,
                line_dash="dash",
                line_color='red',
                annotation_text=f"Median: {df['price'].median():.0f} EUR")
  fig.update_layout(xaxis_title = 'Price (EUR)',
                    yaxis_title = 'Number of listings',
                    bargap=0.1,
                    width=900,
                    height=600,
                    title_font_size=14,
                    xaxis_title_font_size=12,
                    yaxis_title_font_size=12)

# ÖSSZEHASONLÍTÁS
# változók: price, room_type
# Hogyan változik az ár a szobatípusok szerint?
# Boxplot

#MATPLOTLIB - DEFAULT
df.boxplot(column='price', by='room_type')
plt.title('Price by room type - Matplotlib')
plt.suptitle('')
plt.xlabel('Room Type')
plt.ylabel('Price (EUR)')
plt.show()

#MATPLOTLIB - CUSTOM
plt.figure(figsize=(12,8))
df.boxplot(column='price', by='room_type', color='green')
plt.title('Price by room type - Matplotlib', fontsize=14)
plt.suptitle('')
plt.xlabel('Room Type', fontsize=12)
plt.ylabel('Price (EUR)', fontsize=12)
plt.xticks(rotation=45) # azert kell hogy jobban olvashatobb legyen

medians = df.groupby('room_type')['price'].median()
for i, median in enumerate(medians):
  plt.text(i+1,
          median+10,
          f'{median:.0f}',
          ha='center',
          fontsize=9,
          fontweight='bold')

plt.show()

#MATPLOTLIB - BENCHMARK
def plot_matplotlib_box_custom():
  plt.figure(figsize=(12,8))
  df.boxplot(column='price', by='room_type', color='green')
  plt.title('Price by room type - Matplotlib', fontsize=14)
  plt.suptitle('')
  plt.xlabel('Room Type', fontsize=12)
  plt.ylabel('Price (EUR)', fontsize=12)
  plt.xticks(rotation=45) # azert kell hogy jobban olvashatobb legyen

  medians = df.groupby('room_type')['price'].median()
  for i, median in enumerate(medians):
    plt.text(i+1,
            median+10,
            f'{median:.0f}',
            ha='center',
            fontsize=9,
            fontweight='bold')

  plt.close()

#SEABORN - DEFAULT
sns.boxplot(data=df, x='room_type', y='price')
plt.title('Price by room type - Seaborn')
plt.xlabel('Room type')
plt.ylabel('Price(Eur)')
plt.show()

#SEABORN - CUSTOM
plt.figure(figsize=(12,8))
sns.boxplot(data=df, x='room_type', y='price',hue='room_type') #color='green')
plt.title('Price by room type - Seaborn', fontsize=14)
plt.xlabel('Room type', fontsize=12)
plt.ylabel('Price(Eur)', fontsize=12)
plt.xticks(rotation=45)

medians = df.groupby('room_type')['price'].median()
for i, median in enumerate(medians):
  plt.text(i,
          median+10,
          f'{median:.0f}',
          ha='center',
          fontsize=9,
          fontweight='bold')

plt.show()

#SEABORN - BENCHMARK
def plot_seaborn_box_custom():
  plt.figure(figsize=(12,8))
  sns.boxplot(data=df, x='room_type', y='price',hue='room_type') #color='green')
  plt.title('Price by room type - Seaborn', fontsize=14)
  plt.xlabel('Room type', fontsize=12)
  plt.ylabel('Price(Eur)', fontsize=12)
  plt.xticks(rotation=45)

  medians = df.groupby('room_type')['price'].median()
  for i, median in enumerate(medians):
    plt.text(i,
            median+10,
            f'{median:.0f}',
            ha='center',
            fontsize=9,
            fontweight='bold')

  plt.close()

#PLOTLY - DEFAULT
fig = px.box(df,
             x='room_type',
             y='price',
             title="Price by room type - Plotly")
#fig.update_layout(
   # xaxis_title = 'Room type',
    #yaxis_title = 'Price (EUR)')
fig.show()

#PLOTLY - CUSTOM
fig = px.box(df,
            x='room_type',
            y='price',
            title="Price by room type - Plotly",
            color='room_type',
            labels={'room_type': 'Room Type', 'price': 'Price (EUR)'})
medians= df.groupby('room_type')['price'].median()
for room, median in medians.items():
  fig.add_annotation(x=room,
                    y=median+10,
                    text=f'{median:.0f}',
                    showarrow=False,
                    font=dict(size=10, weight='bold'),
                    bgcolor='white',
                    borderpad=2)
fig.update_layout(
    xaxis_title = 'Room type',
    yaxis_title = 'Price (EUR)',
    width=900,
    height=600,
    bargap=0.1)
fig.show()

#PLOTLY - BENCHMARK
def plot_plotly_box_custom():
  fig = px.box(df,
              x='room_type',
              y='price',
              title="Price by room type - Plotly",
              color='room_type',
              labels={'room_type': 'Room Type', 'price': 'Price (EUR)'})
  medians= df.groupby('room_type')['price'].median()
  for room, median in medians.items():
    fig.add_annotation(x=room,
                      y=median+10,
                      text=f'{median:.0f}',
                      showarrow=False,
                      font=dict(size=10, weight='bold'),
                      bgcolor='white',
                      borderpad=2)
  fig.update_layout(
      xaxis_title = 'Room type',
      yaxis_title = 'Price (EUR)',
      width=900,
      height=600,
      bargap=0.1)

# Kapcsolat
# változók: price, availability_365
# Van kapcsolat az ár és a rendelkezésre állás között?
# Scatter plot

#MATPLOTLIB - DEFAULT
plt.scatter(df['price'], df['availability_365'])
plt.title('Price vs Availability - Matplotlib')
plt.xlabel('Price (EUR)')
plt.ylabel('Availability (days per year)')
plt.show()

#MATPLOTLIB - CUSTOM
plt.figure(figsize=(8,6))
plt.scatter(df['price'], df['availability_365'], alpha=0.3, color='green', s=10)
plt.title('Price vs Availability - Matplotlib', fontsize=14)
plt.xlabel('Price (EUR)', fontsize=12)
plt.ylabel('Availability (days per year)', fontsize=12)
plt.grid(True)
plt.show()

#MATPLOTLIB - BENCHMARK
def plot_matplotlib_scat_custom():
  plt.figure(figsize=(8,6))
  plt.scatter(df['price'], df['availability_365'], alpha=0.3, color='green', s=10)
  plt.title('Price vs Availability - Matplotlib', fontsize=14)
  plt.xlabel('Price (EUR)', fontsize=12)
  plt.ylabel('Availability (days per year)', fontsize=12)
  plt.grid(True)
  plt.close()

#SEABORN - DEFAULT
sns.scatterplot(data=df, x='price', y='availability_365')
plt.title('Price vs Availability - Seaborn')
plt.xlabel('Price (EUR)')
plt.ylabel('Availability (days per year)')
plt.show()

#SEABORN - CUSTOM
plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x='price', y='availability_365', alpha=0.3, color='green', s=10)
plt.title('Price vs Availability - Seaborn', fontsize=14)
plt.xlabel('Price (EUR)', fontsize=12)
plt.ylabel('Availability (days per year)', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

#SEABORN - BENCHMARK
def plot_seaborn_scat_custom():
  plt.figure(figsize=(8,6))
  sns.scatterplot(data=df, x='price', y='availability_365', alpha=0.3, color='green', s=10)
  plt.title('Price vs Availability - Seaborn', fontsize=14)
  plt.xlabel('Price (EUR)', fontsize=12)
  plt.ylabel('Availability (days per year)', fontsize=12)
  plt.grid(True, alpha=0.3)
  plt.close()

#PLOTLY - DEFAULT
fig = px.scatter(df,
             x='price',
             y='availability_365',
             title='Price vs Availability - Plotly',
             labels={'price': 'Price (EUR)', 'availability_365': 'Availability (days per year)'})
fig.update_layout(
    xaxis_title='Price (EUR)',
    yaxis_title='Availability (days per year)'
    )
fig.show()

#PLOTLY - CUSTOM
fig = px.scatter(df,
            x='price',
            y='availability_365',
            title='Price vs Availability - Plotly',
            labels={'price': 'Price (EUR)', 'availability_365': 'Availability (days per year)'},
            color_discrete_sequence=['green'],
            opacity=0.4)
fig.update_traces(marker=dict(size=4))
fig.update_layout(
    xaxis_title='Price (EUR)',
    yaxis_title='Availability (days per year)',
    width=800)
fig.show()

#PLOTLY - BENCHMARK
def plot_plotly_scat_custom():
  fig = px.scatter(df,
              x='price',
              y='availability_365',
              title='Price vs Availability - Plotly',
              labels={'price': 'Price (EUR)', 'availability_365': 'Availability (days per year)'},
              color_discrete_sequence=['green'],
              opacity=0.4)
  fig.update_traces(marker=dict(size=4))
  fig.update_layout(
      xaxis_title='Price (EUR)',
      yaxis_title='Availability (days per year)',
      width=800)

results = []

for name, func in [
    ("matplotlib_hist", plot_matplotlib_hist_custom),
    ("seaborn_hist", plot_seaborn_hist_custom),
    ("plotly_hist", plot_plotly_hist_custom),
    ("matplotlib_box", plot_matplotlib_box_custom),
    ("seaborn_box", plot_seaborn_box_custom),
    ("plotly_box", plot_plotly_box_custom),
    ("matplotlib_scatter", plot_matplotlib_scat_custom),
    ("seaborn_scatter", plot_seaborn_scat_custom),
    ("plotly_scatter", plot_plotly_scat_custom)
]:
    mean, std = benchmark(func, repeats=10)

    results.append({
        "library": name,
        "mean_time": mean,
        "std_time": std
    })

#FUTÁSI IDŐK EREDMÉNYE
results_df = pd.DataFrame(results)
print(results_df)